### ISSUE TITLE
s2a_datetime_picker format

### ISSUE THREAD

**Issue by pjam** [symfony2admingenerator/FormExtensionsBundle#48]
Hi.

I can't seem to set the format for this widget. When I try to set the format in the yml, it throws an exception saying that it only allows the HTML5 format. I've checked the form type and there is the limitation set in the resolver's setAllowedValues method.

What is the way to change the format for this wigdet?

**Comment by bobvandevijver** [comment]
The widget uses two format options, so that might be your problem. I currently use this following (in PHP, but you should be able to convert that to yml):

```php
$resolver->setDefaults(array(
        'widget' => 'single_text',
        'format' => self::FORMAT_SF,
        'width'  => NULL,
        'config' => array(
            'format'     => self::FORMAT_JS,
            'useCurrent' => false,
            'sideBySide' => true,
            'stepping'   => 5,
            'showClear'  => true,
            'showClose'  => true,
            'icons'      => array(
                'time' => "fa fa-clock-o",
                'date' => "fa fa-calendar",
                'up'   => "fa fa-arrow-up",
                'down' => "fa fa-arrow-down"
            )
        )
    ));
```

(I've extended the s2a_datetime_picker so that I always have the defaults I need). 

Furthermore, I've fixed the top format on `self::FORMAT_JS` in the allowed values in the form definition: 

```PHP
 $resolver->setAllowedValues(array(
        'widget' => array('single_text'),
        'format' => array(self::FORMAT_SF),
    ));
```

Probably because otherwise I get the same order. So, in short, try editing the `form => self::FORMAT_JS` option.

**Comment by bobvandevijver** [comment]
@pjam For complete reference: https://gist.github.com/bobvandevijver/b58ad53a9be0b1f0d244

**Comment by pjam** [comment]
Hi @bobvandevijver 

After reading you reply I found what I wanted. When I mentioned the yml, I was refering to the generator yml. The format I needed to change was the one under config. So I did it with:
```yaml
field_name:
    formType: s2a_datetime_picker
    formOptions:
      config:
        format: DD-MM-YYYY
```

Thanks!

**Comment by bobvandevijver** [comment]
Great!
