### ISSUE TITLE
Support for twig 2

### ISSUE THREAD

**Issue by TheCelavi** [symfony2admingenerator/FormExtensionsBundle#77]
Twig version is locked on 1.x.

Is support for v2 is planned?

**Comment by bobvandevijver** [comment]
There is currently not anyone really working in this bundle: however, if you can create an PR which gives us Twig 2 support, I'm more than happy to take a look at it.

**Comment by TheCelavi** [comment]
Ok, will do that. 

While you are here, I have looked on activity log in regards go GeneratorBundle, it is kinda low.... A lot of things happening right now, bundless symfony apps and so on...

These bundles are going to continue with their lives, right?

**Comment by bobvandevijver** [comment]
Well, I'm still using both bundles at the moment (and I'm not planning to end that), so I will continue to give them the updates they need in order to be able to keep using them with my projects. 

However, my time is currently very limited. I would like to do more, but I have to rely a little bit more on the community I guess. Not sure how the others are, but they probably are in the same kind of situation.

**Comment by sescandell** [comment]
Done
